package iut.sae.saecentressante.views;



import iut.sae.saecentressante.controllers.IGraphe;
import iut.sae.saecentressante.models.FileImplement;
import iut.sae.saecentressante.models.Graphe;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/**
 * JFrame representant le menu d'accueil.
 * 
 * @author Jason GUGLIELMETTO
 * @version 1.1
 */
public class MenuFrame extends javax.swing.JFrame {
    
    
    
    /**
     * Le graphe a afficher.
     * 
     * @see Graphe
     */
    private Graphe g;
    
    /**
     * L'objet Controller qui va relier la JFrame au Graphe.
     * 
     * @see IGraphe
     * @see Controller
     */
    private IGraphe igr;
    
    

    /**
     * Constructeur de la MenuFrame.
     * 
     * @param igr L'objet Controller etablissant le lien entre la JFrame et le Graphe.
     * @see IGraphe
     * @see Controller
     */
    public MenuFrame(IGraphe igr) {
        this.setIconImage(new ImageIcon("./src/main/java/iut/sae/saecentressante/assets/ambulance.png").getImage());
        this.igr = igr;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJPanel = new javax.swing.JPanel() {
            public void paintComponent(Graphics g) {
                try {
                    BufferedImage img = ImageIO.read(new File("./src/main/java/iut/sae/saecentressante/assets/fond_ambulance.png"));
                    g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);
                } catch (IOException ex) {
                    Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
        buttonsPanel = new javax.swing.JPanel();
        newGraphJButton = new javax.swing.JButton();
        loadingGraphJButton = new javax.swing.JButton();
        displayGraphJButton = new javax.swing.JButton();
        personalGraphJButton = new javax.swing.JButton();
        quitJButton = new javax.swing.JButton();
        titlePanel = new javax.swing.JPanel();
        title1JLabel = new javax.swing.JLabel();
        title2JLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aide décisionnelle pour centres de sante");
        setMinimumSize(new java.awt.Dimension(650, 400));
        setResizable(false);

        buttonsPanel.setBackground(new java.awt.Color(255, 255, 255));
        buttonsPanel.setLayout(new java.awt.GridLayout(5, 0, 0, 12));

        newGraphJButton.setText("Nouveau graphe");
        newGraphJButton.setEnabled(false);
        buttonsPanel.add(newGraphJButton);

        loadingGraphJButton.setText("Charger un graphe");
        loadingGraphJButton.setRequestFocusEnabled(false);
        loadingGraphJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadingGraphJButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(loadingGraphJButton);

        displayGraphJButton.setText("Visualiser le graphe");
        displayGraphJButton.setEnabled(false);
        displayGraphJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayGraphJButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(displayGraphJButton);

        personalGraphJButton.setText("Visualiser graphe perso");
        personalGraphJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalGraphJButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(personalGraphJButton);

        quitJButton.setText("Quitter");
        quitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJButtonActionPerformed(evt);
            }
        });
        buttonsPanel.add(quitJButton);

        titlePanel.setBackground(new java.awt.Color(255, 255, 255));

        title1JLabel.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        title1JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1JLabel.setText("Bienvenue sur l'application");
        titlePanel.add(title1JLabel);

        title2JLabel.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        title2JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2JLabel.setText("Aide décisionnelle pour centres de santé");
        titlePanel.add(title2JLabel);

        jLabel1.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        jLabel1.setText("G2S2A - BOURBON Mehdi, GUGLIELMETTO Jason, BABA Kerredine");
        titlePanel.add(jLabel1);

        javax.swing.GroupLayout mainJPanelLayout = new javax.swing.GroupLayout(mainJPanel);
        mainJPanel.setLayout(mainJPanelLayout);
        mainJPanelLayout.setHorizontalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJPanelLayout.createSequentialGroup()
                        .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJPanelLayout.createSequentialGroup()
                        .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
        );
        mainJPanelLayout.setVerticalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        getContentPane().add(mainJPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Charge un graphe en memoire.
     * 
     * @param evt Un MouseEvent.
     * @see Graphe
     */
    private void loadingGraphJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadingGraphJButtonActionPerformed
        try {
            g = FileImplement.loadGraphe();
            displayGraphJButton.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erreur dans le chargement des fichiers.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loadingGraphJButtonActionPerformed

    /**
     * Affiche la GraphFrame correspondante au graphe charge en memoire.
     * 
     * @param evt Un MouseEvent.
     * @see GraphFrame
     */
    private void displayGraphJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayGraphJButtonActionPerformed
        this.dispose();
        new GraphFrame(g, igr).setVisible(true);
    }//GEN-LAST:event_displayGraphJButtonActionPerformed

    /**
     * Quitte.
     * 
     * @param evt Un MouseEvent.
     */
    private void quitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitJButtonActionPerformed

    /**
     * Ouvre une GraphFrame avec le GraphePerso.
     * 
     * @param evt Un MouseEvent.
     * @see GraphePerso
     * @see GraphFrame
     */
    private void personalGraphJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalGraphJButtonActionPerformed
        this.setVisible(false);
        new GraphFrame(this.igr.returnGraphePerso(), igr).setVisible(true);
    }//GEN-LAST:event_personalGraphJButtonActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton displayGraphJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loadingGraphJButton;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JButton newGraphJButton;
    private javax.swing.JButton personalGraphJButton;
    private javax.swing.JButton quitJButton;
    private javax.swing.JLabel title1JLabel;
    private javax.swing.JLabel title2JLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
